### ISSUE TITLE
vfox install golang失败

### ISSUE THREAD

**Issue by zoze0** [ShizheChang/vfox-plugin-golang#8]
```rust
➜  ~ vfox install golang
plugin [PreInstall] method error: no version number provided
```

**Comment by jan-bar** [comment]
You should use `vfox i golang@1.22.1`

or

`vfox search golang`  to select version

**Comment by bytemain** [comment]
@jan-bar @aooohan  how about we provide a prompt:
```
> no version number provided, found latest version: 1.21.0, would you like to install it (y/n)?
```

**Comment by aooohan** [comment]
> @jan-bar @aooohan how about we provide a prompt:
> 
> ```
> > no version number provided, found latest version: 1.21.0, would you like to install it (y/n)?
> ```

I think it's pretty good, but maybe it requires the plugin to sort the return of `Available` hook? How else would we know what the latest version is?

**Comment by zoze0** [comment]
Thanks, It works. 

But using the latest version by default might be even smoother      (just like sdkman,I've used it for a long time)

**Comment by zoze0** [comment]
或者是install指定版本时，安装对应版本
install未指定版本时，直接运行search结果,然后提供用户选择安装如何？省去额外search一次

```sh
➜  ~ vfox install golang
Please select a version of golang [type to search]: 
->  v1.22.1 (stable)
   v1.21.8 (stable)
   v1.22.0
   v1.21.7
   v1.21.6
   v1.21.5
   v1.21.4
   v1.21.3
   v1.21.2
   v1.21.1
   v1.21.0
   v1.22rc2
   v1.22rc1
   v1.21rc4
   v1.21rc3
   v1.21rc2
Press ↑/↓ to select and press ←/→ to page, and press Enter to confirm
```

**Comment by aooohan** [comment]
> 或者是install指定版本时，安装对应版本 install未指定版本时，直接运行search结果,然后提供用户选择安装如何？省去额外search一次
> 

跟 https://github.com/version-fox/vfox-golang/issues/8#issuecomment-2030960968 说的是一个意思, 应该放到vfox上去做.
